### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by MikeVezina** [hate-bug/JUMP_IN_GAME#2]
**Feedback:**

- Either specify a main class when you create the Jar file (so that I can run it with `java -jar Jump_IN.jar`), or provide the appropriate commands in the Readme so that I can start the game.

- The Command class is a bit smelly. Not all commands make use of three words. This class could be improved (i.e. generalized for all types of commands).

- Good job with using the Piece interface, but you could have done better by turning it into an abstract class and moving the pieceName and location from each of the sub-classes up to Piece.

- You should not be hard coding the piece names in an enum, but rather generating the piece names as strings. Make sure to consider this for future milestones as this is smelly. 

- The pieceName enum is not included on the UML diagram (it should be shown as a class).

- Regarding sequence diagrams, the dotted lines with arrows are reserved for return values (or to show flow returning to the calling objects). You use these arrows incorrectly to show method calls.

**Mark: 7/10** (everything works, but the above feedback needs to be addressed for the next milestone)

**Comment by hate-bug** [comment]
For sequence diagram, I followed the formart from professor's slides, we will change that in the next milestone. 
For piecenames: It's actualy part of the command words. We put them inside Enum to avoid typo in the code and if there is any more piece nedd to be added later, we can always modify the Enum class. It's very similiar to the command words in Zuul-bad lab. 
In the requirement doc, Professor just mentioned we need to include an executable JAR file, we didn't know we should specify the main class, we will improve that in the next milestone. 
For all those explanation above, can we get a bit more mark for M1? As our code is working propely and we finished&documented everything.

**Comment by MikeVezina** [comment]
I didn't take off marks for any smelly code, I only stated it so you could improve for the next milestone.  Also, please make sure you give a more appropriate name to your image files, so that I know which one is the UML class diagram and which one is the sequence diagram.

You lost marks on the following points:

1. Failed to provide instructions on how to start your program. Yes, you provided a Jar file, but you should have instructions on how to run the game. Otherwise, it requires searching through your code to find the main class. This should be included in your readme.

2. pieceNames is an enum, and it is missing in your UML diagram. Even though it is embedded in the Piece class, it still needs to be indicated on the UML class diagram. This also goes for CommandWords. Even though it is buried in another class, this still needs to be shown in the UML class diagram.

3. You incorrectly used the return arrows on the sequence diagrams. The flow of the sequence diagram was a bit confusing to follow. 

I'm happy to change your mark to a 7.5/10, but I think that it is important to make sure everything is shown on the UML and sequence diagrams, and that it should be shown correctly.

**Comment by chenjunyuan1998** [comment]
Sir, I still have a question on the marking scheme. First of all thank you for correcting us and put effort on our milestone and I totally agree with you about the mistake you mentioned that we did not deal with good enough and we will improve that. But this milestone was worth 10 marks total. In my understanding, I think the code part should be the major part of these 10 marks. And readme file, a uml or a sequence diagram  worth probably about 1 mark each. Correct me if I made the assumption wrong. And I think we may deserve more points in the milestone, for example, we were missing the enum part in the UML, but I think the rest of the part is still counting for mark right? It is not that fair to deduct the entire 1 point just because of we missed 1 part of the entire section. Also about the readme, missing the instruction of how to play the game does not mean that we did not do it at all. We follow the instruction of the PDF. And you just gave us a 0 because of we missed one part of it. Could the marking scheme be with a little bit more flexibility? Or the Prof said deduct all the mark for one section no matter how many mistakes they made, if they made it just gives a 0. Such as we have 4 or 5 parts in readme, we did not do 1 part so deduct 1/4 or 1/5 of the total mark. I asked about the marks of the other groups, their TA did something like that, at least not just deducting 1 mark because of we made 1 part incorrect in the entire section.  Even if those section were worth 2 marks , deduct half of them because of 1 mistake isn't that reasonable Since our code maybe is a little bit smelly in some terms but it is working totally fine. We could get all the marks at least for coding part right? Could you just make a brief discuss with us about the marking scheme and if it is possible I think we may deserve more marks on this milestone.Thank you very much for reading this.

**Comment by MikeVezina** [comment]
I've looked over your solution again, and I would consider a 7.5 generous for the solution that you submitted. Although the coding is important, proper design and documentation is just as important. 

After looking into more detail, your design decision defence in your readme file is lacking detail. The information you stated does not defend or explain your design decisions at all, it conveys the same amount of information as a UML diagram. You needed to go into detail about why your design makes sense. Some groups submitted multiple-page documents going into detail about their design and how their design was feasible (compared to designing their milestone in a different way). **I failed to deduct marks for this on your submission**, and I will not adjust your grade to lower your mark, but I will be looking for this in the next milestone. It doesn't have to be a multi-page document, but you must at least defend your design decisions and explain why this design was chosen.

Your sequence diagram is incorrect as you incorrectly used the sequence diagram arrows. Full marks should be deducted, as you failed to follow the proper format for a sequence diagram. You also failed to provide instructions on how to start your game (incorrect documentation). 

I understand what you are trying to suggest, but I believe that the marking scheme that was used is fair. If we were to follow the marking scheme you suggested (only take one mark off if no artifact was submitted and heavily weight the grades for coding), then people would be able to hypothetically get 7/10 if they just submit working code (and no readme or diagrams submitted). This should **not** be the case because the importance of UML, Sequence diagram, and documentation should also be stressed by the rubric. 

I think a 7.5/10 is generous for your solution, and I believe the rubric used is fair.

**Comment by chenjunyuan1998** [comment]
Thanks, That was a fair explanation, we just want to know the marking scheme some stuff like that. Because we were curious about why we got deduct on one mistake in one section. Since we know that we have several mistakes in the section, that makes sense
